### ISSUE TITLE
Incompatible with qBittorrent v4.5.0

### ISSUE THREAD

**Issue by DcR-NL** [dracula/qbittorrent#12]
Seems incompatible with qBittorrent v4.5.0. Outputs labels/text as functions (?) instead of the actual text. Didn't see this issue on v4.4.5.

![image](https://user-images.githubusercontent.com/1094952/204160656-2b221afe-f866-45e2-ba2b-a73bac87eb78.png)

**Comment by MahdiMirzade** [comment]
This issue is now fixed by the latest theme update and re-writing the stylesheet.
Download it by [clicking here](https://github.com/dracula/qbittorrent/raw/master/dracula.qbtheme).

Reopen the issue if necessary.

**Comment by DcR-NL** [comment]
@MahdiMirzade I'm sorry, I forgot to mention that I'm seeing this on the WebUI. As a Headless Docker Linux user, I forget something like the GUI even existed. For me, the issue is still there on the latest commit (61987d90d0a0fa3ccb9bd8304c5ee4ca9c77b73c) and I don't have the permission to reopen the issue.

![image](https://user-images.githubusercontent.com/1094952/204358403-0b2c6deb-8b0b-4a22-b60c-00959dbbaa60.png)

**Comment by MahdiMirzade** [comment]
Hello @DcR-NL , I'm sorry for not realizing this is a webui issue.
Please refer to #14 for more information about this issue.

I've matched the webui theme to meet the latest changes from qBittorrent's source code, but I can't test it since qbittorrent-nox v4.5.0 is not available for my distribution, therefore I'd appreciate if you reinstalled the theme, and report after you've tested the https://github.com/dracula/qbittorrent/commit/ee386fffc39888dc3b72d0df1566f9c8683390cd commit.

Best Regards, Mahdi.
